name: Integration tests

on:
  pull_request:

env:
  GO111MODULE: "on"
  CI: "GitHub"

jobs:
  tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3

      - name: Tests
        run: |
          docker compose -f deployments/docker-compose.test.yaml -p anti-brute-force-test up --exit-code-from tests --attach tests && \
          EXIT_CODE=$? && \
          docker compose -f deployments/docker-compose.test.yaml -p anti-brute-force-test down && \
          echo "command exited with $EXIT_CODE" && \
          exit $EXIT_CODE
        working-directory: ./
